const COURSES_SEED = [
  // 1ST YEAR - 1ST TERM
  { yearLevel:"1st Year", term:"1st", code:"CPE100",    name:"Computer Engineering as a Discipline",          prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"CPE001L",   name:"Computer Fundamentals and Programming 1 (Lab)", prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"CHM031",    name:"Chemistry for Engineers",                       prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"CHM031L",   name:"Chemistry for Engineers (Laboratory)",          prerequisites:"", coRequisites:"CHM031", units:1, status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"SS021",     name:"Understanding the Self",                        prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"ENG023",    name:"Receptive Communication Skills",                prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"MATH031",   name:"Mathematics for Engineers",                     prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"NSTP010",   name:"National Service Training Program 1",           prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"1st", code:"VE021",     name:"Life Coaching Series 1",                        prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  // 1ST YEAR - 2ND TERM
  { yearLevel:"1st Year", term:"2nd", code:"CPE003L",   name:"Advanced Programming Techniques (Lab)",         prerequisites:"CPE001L", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"DRAW021W",  name:"Engineering Drawing 1",                         prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"ENG024",    name:"Writing for Academic Studies",                  prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"MATH035",   name:"Mathematics in the Modern World",               prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"MATH041",   name:"Engineering Calculus 1",                        prerequisites:"MATH031", coRequisites:"", units:4, status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"HUM021",    name:"Logic and Critical Thinking",                   prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"NSTP011P",  name:"National Service Training Program 2 (Paired)",  prerequisites:"NSTP010", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"1st Year", term:"2nd", code:"VE022",     name:"Life Coaching Series 2",                        prerequisites:"VE021", coRequisites:"", units:1, status:"Future" },
  // 1ST YEAR - 3RD TERM
  { yearLevel:"1st Year", term:"3rd", code:"DRAW023L-1",name:"Computer-Aided Drafting (Laboratory)",          prerequisites:"DRAW021W", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"CPE141L",   name:"Programming Logic and Design (Lab)",            prerequisites:"CPE001L", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"EE099L",    name:"Basic Electricity and Electronics Workshop (Lab)", prerequisites:"", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"HUM039",    name:"Ethics",                                        prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"MATH042",   name:"Engineering Calculus 2",                        prerequisites:"MATH041", coRequisites:"", units:4, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"PE001",     name:"Physical Activities Toward Health and Fitness 1", prerequisites:"", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"PHY035",    name:"Physics for Engineers",                         prerequisites:"MATH041", coRequisites:"", units:4, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"PHY035L",   name:"Physics for Engineers (Laboratory)",            prerequisites:"MATH041", coRequisites:"PHY035", units:1, status:"Future" },
  { yearLevel:"1st Year", term:"3rd", code:"VE023",     name:"Life Coaching Series 3",                        prerequisites:"VE022", coRequisites:"", units:1, status:"Future" },
  // 2ND YEAR - 1ST TERM
  { yearLevel:"2nd Year", term:"1st", code:"CPE105-1",  name:"Discrete Mathematics",                          prerequisites:"MATH041", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"CPE142L",   name:"Object Oriented Programming (Lab)",             prerequisites:"CPE141L", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"ECE121L",   name:"Computer-Aided Calculations (Laboratory)",      prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"EE101-3",   name:"Fundamentals of Electrical Circuits",           prerequisites:"MATH042, PHY035", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"EE101L-3",  name:"Fundamentals of Electrical Circuits (Laboratory)", prerequisites:"PHY035L", coRequisites:"EE101-3", units:1, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"IE101-1",   name:"Engineering Data Analysis",                     prerequisites:"MATH041", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"MATH056",   name:"Differential Equations",                        prerequisites:"MATH042", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"PE002",     name:"Physical Activities Toward Health and Fitness 2", prerequisites:"", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"2nd Year", term:"1st", code:"SS085",     name:"Philippine Indigenous Communities",             prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  // 2ND YEAR - 2ND TERM
  { yearLevel:"2nd Year", term:"2nd", code:"CS105L",    name:"Data Structures and Algorithms (Laboratory)",   prerequisites:"CPE142L", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"DS100L",    name:"Applied Data Science Laboratory",               prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"ECE101-3",  name:"Fundamental of Electronic Circuits",            prerequisites:"EE101-3", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"ECE101L-3", name:"Fundamental of Electronic Circuits (Laboratory)", prerequisites:"EE101L-3", coRequisites:"ECE101-3", units:1, status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"EECO102",   name:"Engineering Economy",                           prerequisites:"IE101-1", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"ENG041",    name:"Purposive Communication",                       prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"GEELEC01",  name:"GE Elective 1 (Gender and Society)",            prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"MATH116",   name:"Advanced Engineering Mathematics",              prerequisites:"MATH056", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"2nd", code:"PE003",     name:"Physical Activities Toward Health and Fitness 3", prerequisites:"", coRequisites:"", units:2, status:"Future" },
  // 2ND YEAR - 3RD TERM
  { yearLevel:"2nd Year", term:"3rd", code:"ACT099",    name:"Accounting for Non-Accountant",                 prerequisites:"", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"CPE101-1",  name:"Digital Electronics: Logic Circuits and Design",prerequisites:"ECE101-3", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"CPE101L-1", name:"Digital Electronics: Logic Circuits and Design (Lab)", prerequisites:"ECE101L-3", coRequisites:"CPE101-1", units:1, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"CPE106-1",  name:"Data and Digital Communications",               prerequisites:"ECE101-3", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"CPE121L-1", name:"Computer Engineering Drafting and Design (Lab)",prerequisites:"ECE101-3", coRequisites:"CPE101-1", units:1, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"EMGT100",   name:"Engineering Management",                        prerequisites:"EECO102", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"EMGT100L",  name:"Project Management (Laboratory)",               prerequisites:"EECO102", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"MATH161",   name:"Numerical Methods",                             prerequisites:"MATH116", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"MATH161L",  name:"Numerical Methods (Laboratory)",                prerequisites:"MATH116, ECE121L", coRequisites:"MATH161", units:1, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"MATH800E",  name:"Engineering Mathematics Exit Exam",             prerequisites:"IE101-1, MATH116", coRequisites:"", units:0, status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"SS038",     name:"The Life and Works of Jose Rizal",              prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"2nd Year", term:"3rd", code:"PE004",     name:"Physical Activities Toward Health and Fitness 4", prerequisites:"PE001, PE002", coRequisites:"", units:2, status:"Future" },
  // 3RD YEAR - 1ST TERM
  { yearLevel:"3rd Year", term:"1st", code:"CPE103-4",  name:"Microprocessors",                               prerequisites:"CPE101-1", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE103L-4", name:"Microprocessors (Laboratory)",                  prerequisites:"CPE101L-1", coRequisites:"CPE103-4", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE109-1",  name:"Computer Networks and Security",                prerequisites:"CPE106-1", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE109L-1", name:"Computer Networks and Security (Laboratory)",   prerequisites:"CPE106-1", coRequisites:"CPE109-1", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE126",    name:"Artificial Intelligence",                       prerequisites:"DS100L", coRequisites:"", units:2,  status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE126L",   name:"Artificial Intelligence (Laboratory)",          prerequisites:"DS100L", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE104L-1", name:"Intro to Hardware Description Language (Lab)",  prerequisites:"CPE141L, CPE101-1", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"CPE143L",   name:"Web Design and Development (Laboratory)",       prerequisites:"CPE142L", coRequisites:"", units:2,  status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"SS036",     name:"Science, Technology, and Society",              prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"1st", code:"TEC100-2",  name:"Technopreneurship",                             prerequisites:"EMGT100, ACT099", coRequisites:"", units:3, status:"Future" },
  // 3RD YEAR - 2ND TERM
  { yearLevel:"3rd Year", term:"2nd", code:"CPE108",    name:"Fundamentals of Mixed Signals and Sensors",     prerequisites:"ECE101-3", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"CPE108L",   name:"Fundamentals of Mixed Signals and Sensors (Lab)", prerequisites:"ECE101L-3", coRequisites:"ECE101-3", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"CPE107-1",  name:"Software Design",                               prerequisites:"CS105L", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"CPE107L-1", name:"Software Design (Laboratory)",                  prerequisites:"CS105L", coRequisites:"CPE107-1", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"CPE144L",   name:"Mobile Application Development (Laboratory)",   prerequisites:"CPE142L", coRequisites:"", units:2, status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"CPE801E",   name:"Engineering Sciences Exit Exam",                prerequisites:"CHM031, PHY035, EECO102", coRequisites:"", units:0, status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"ECE130",    name:"Feedback and Control Systems",                  prerequisites:"MATH116", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"NETA172P-1",name:"CCNA Routing and Switching 1 (Paired)",         prerequisites:"PHY035", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"RES101",    name:"Methods of Research",                           prerequisites:"IE101-1, ENG024", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"3rd Year", term:"2nd", code:"SS022",     name:"Readings in Philippine History",                prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  // 3RD YEAR - 3RD TERM
  { yearLevel:"3rd Year", term:"3rd", code:"CAP200D",   name:"Capstone Design / Thesis 1 (Laboratory)",       prerequisites:"RES101", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPE112-1",  name:"Embedded Systems",                              prerequisites:"CPE103-4", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPE112L-1", name:"Embedded Systems (Laboratory)",                 prerequisites:"CPE103L-4", coRequisites:"CPE112-1", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPE181",    name:"CPE Laws and Professional Practice",            prerequisites:"HUM039", coRequisites:"", units:2,  status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPE151",    name:"Operating Systems",                             prerequisites:"CS105L", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPE151L",   name:"Operating Systems (Laboratory)",                prerequisites:"CS105L", coRequisites:"CPE151", units:1, status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPE802E",   name:"Computer Engineering 1 Exit Exam",              prerequisites:"CPE142L, CPE143L, CS105L, CPE107-1", coRequisites:"", units:0, status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"CPEELEC01", name:"CPE Elective 1 (Paired)",                       prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"EENV102",   name:"Environmental Science and Engineering",         prerequisites:"CHM031", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"3rd Year", term:"3rd", code:"GEELEC02",  name:"GE Elective 2 (ICC)",                           prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  // 4TH YEAR - 1ST TERM
  { yearLevel:"4th Year", term:"1st", code:"CAP200D-1", name:"Capstone Design / Thesis 2 (Laboratory)",       prerequisites:"CAP200D", coRequisites:"", units:1,  status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPE110-1",  name:"Emerging Technologies in CPE",                  prerequisites:"CPE103-4", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPE113-1",  name:"Digital Signal Processing",                     prerequisites:"ECE130", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPE113L-1", name:"Digital Signal Processing (Laboratory)",        prerequisites:"ECE130, ECE121L", coRequisites:"CPE113-1", units:1, status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPE131-1",  name:"Computer Architecture and Organization",        prerequisites:"CPE103-4", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPE131L-1", name:"Computer Architecture and Organization (Lab)",  prerequisites:"CPE103L-4", coRequisites:"CPE131-1", units:1, status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPEELEC02", name:"CPE Elective 2 (Paired)",                       prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"4th Year", term:"1st", code:"CPE198-3",  name:"CPE Correlation 1",                             prerequisites:"MATH800E, CPE801E", coRequisites:"", units:1, status:"Future" },
  // 4TH YEAR - 2ND TERM
  { yearLevel:"4th Year", term:"2nd", code:"CAP200D-2", name:"Capstone Design / Thesis 3 (Laboratory)",       prerequisites:"CAP200D-1", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"4th Year", term:"2nd", code:"CPE803E",   name:"Computer Engineering 2 Exit Exam",              prerequisites:"CPE109-1, CPE110-1, CPE113-1, CPE151, CPE181", coRequisites:"CPE131-1", units:0, status:"Future" },
  { yearLevel:"4th Year", term:"2nd", code:"CPEELEC03", name:"CPE Elective 3 (Paired)",                       prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"4th Year", term:"2nd", code:"HUM034",    name:"Art Appreciation",                              prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"4th Year", term:"2nd", code:"SS023",     name:"The Contemporary World",                        prerequisites:"", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"4th Year", term:"2nd", code:"CPE198-4",  name:"CPE Correlation 2",                             prerequisites:"CPE802E, CPE803E", coRequisites:"", units:1, status:"Future" },
  // 4TH YEAR - 3RD TERM
  { yearLevel:"4th Year", term:"3rd", code:"CPE191F-1", name:"CPE Seminars and Field Trips (Field)",          prerequisites:"CPE109-1, CPE144L", coRequisites:"", units:1, status:"Future" },
  { yearLevel:"4th Year", term:"3rd", code:"CPE199R-1", name:"CPE Practicum",                                 prerequisites:"CPE143L, CS105L, ECE101-3, HUM039", coRequisites:"", units:3, status:"Future" },
  { yearLevel:"4th Year", term:"3rd", code:"SAF102",    name:"Basic Occupational Safety and Health",          prerequisites:"CHM031", coRequisites:"", units:3,  status:"Future" },
  { yearLevel:"4th Year", term:"3rd", code:"SGE101",    name:"Student Global Experience",                     prerequisites:"", coRequisites:"", units:0,  status:"Future" },
];

module.exports = COURSES_SEED;
